### ISSUE TITLE
error start checking BIP39 phrases

### ISSUE THREAD

**Issue by azv1** [TheRealLordFractal/Bip39Generator#6]
~/Bip39Generator# ./brain12words.py -n 9000000000000000000 | ../brai                                                                         nflayer/brainflayer -v -m tablefile.tab -o foundkeys.txt -b testfile.blm
failed to open bloom filter 'testfile.blm': No such file or directory
Traceback (most recent call last):
  File "./brain12words.py", line 98, in <module>
    sys.exit(main())
  File "./brain12words.py", line 89, in main
    generate(prefix, number)
  File "./brain12words.py", line 50, in generate
    print " %s %s %s %s %s %s %s %s %s %s %s %s " % (word1.rstrip(), word2.rstri                                                                         p(), word3.rstrip(), word4.rstrip(), word5.rstrip(), word6.rstrip(), word7.rstri                                                                         p(), word8.rstrip(), word9.rstrip(), word10.rstrip(), word11.rstrip(), word12.rs                                                                         trip())
IOError: [Errno 32] Broken pipe

**Comment by Mezantrop74** [comment]
Put the generator file in the brainflayer folder and run
sudo python generator.py -n xxxxxxxx | sudo ./brainflayer -v -m tablefile.tab -o foundkeys.txt -b testfile.blf
